'use client';

import React, { useState, useRef } from 'react';
import { Clipboard, Check, FileDown, Loader2 } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';

interface SummaryCardProps {
    summary: string;
}

export default function SummaryCard({ summary }: SummaryCardProps) {
    const [copied, setCopied] = useState(false);
    const [isExporting, setIsExporting] = useState(false);
    const cardRef = useRef<HTMLDivElement>(null);

    const copyToClipboard = () => {
        navigator.clipboard.writeText(summary);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const downloadPDF = async () => {
        if (!cardRef.current) return;

        setIsExporting(true);
        try {
            const element = cardRef.current;
            const canvas = await html2canvas(element, {
                scale: 2,
                useCORS: true,
                logging: false,
                backgroundColor: '#ffffff',
            });

            const imgData = canvas.toDataURL('image/png');
            const pdf = new jsPDF('p', 'mm', 'a4');
            const imgProps = pdf.getImageProperties(imgData);
            const pdfWidth = pdf.internal.pageSize.getWidth();
            const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;

            pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
            pdf.save('Lurnix_AI_Summary.pdf');
        } catch (error) {
            console.error('PDF Generation failed:', error);
            alert('Failed to generate PDF. Please try again.');
        } finally {
            setIsExporting(false);
        }
    };

    return (
        <div className="w-full space-y-4 animate-in fade-in slide-in-from-bottom-4 duration-500">
            <div className="flex justify-end space-x-2">
                <button
                    onClick={copyToClipboard}
                    className="flex items-center space-x-2 px-4 py-2 bg-white border border-gray-200 text-gray-600 hover:text-amber-600 hover:border-amber-200 hover:bg-amber-50 rounded-xl transition-all shadow-sm text-sm font-medium"
                >
                    {copied ? (
                        <>
                            <Check className="w-4 h-4 text-green-500" />
                            <span>Copied!</span>
                        </>
                    ) : (
                        <>
                            <Clipboard className="w-4 h-4" />
                            <span>Copy Text</span>
                        </>
                    )}
                </button>

                <button
                    onClick={downloadPDF}
                    disabled={isExporting}
                    className="flex items-center space-x-2 px-4 py-2 bg-gradient-to-r from-amber-500 to-yellow-500 text-white hover:shadow-lg hover:-translate-y-0.5 disabled:bg-gray-400 disabled:shadow-none disabled:hover:translate-y-0 disabled:opacity-50 rounded-xl transition-all shadow-md text-sm font-medium"
                >
                    {isExporting ? (
                        <>
                            <Loader2 className="w-4 h-4 animate-spin" />
                            <span>Exporting...</span>
                        </>
                    ) : (
                        <>
                            <FileDown className="w-4 h-4" />
                            <span>Download PDF</span>
                        </>
                    )}
                </button>
            </div >

            <div
                ref={cardRef}
                className="w-full bg-white border border-gray-100 rounded-2xl shadow-premium overflow-hidden border-t-4 border-t-amber-500"
            >
                <div className="px-8 py-6 border-b border-gray-50 bg-gray-50/30">
                    <div className="flex items-center space-x-3">
                        <div className="w-2 h-8 bg-amber-500 rounded-full" />
                        <h3 className="text-xl font-bold text-gray-900">Summary Report</h3>
                    </div>
                    <p className="text-xs text-gray-400 mt-1 uppercase tracking-wider font-semibold">Generated by Lurnix AI • {new Date().toLocaleDateString()}</p>
                </div>

                <div className="p-8 md:p-10">
                    <div className="prose prose-slate prose-headings:text-amber-900 prose-headings:font-bold prose-p:text-gray-700 prose-li:text-gray-700 prose-strong:text-amber-700 max-w-none">
                        <ReactMarkdown remarkPlugins={[remarkGfm]}>
                            {summary}
                        </ReactMarkdown>
                    </div>
                </div>

                <div className="px-8 py-4 bg-gray-50/50 border-t border-gray-50 text-center">
                    <p className="text-[10px] text-gray-400 font-medium tracking-widest uppercase">
                        Designed for Academic Excellence
                    </p>
                </div>
            </div>
        </div >
    );
}
